version: "3.9"

services:
  hydra-node-1:
    image: hydra-node:latest
    profiles:
      - hydra-node
      - delegate-server
    volumes:
      - ./data/hydra-keys:/keys:ro
      - ./data/credentials:/devnet/credentials
      - ./${CLUSTER_WORKDIR}:/devnet
    ports:
      - "4001:4001"
    command:
      [ "--node-id", "1"
      , "--api-host", "0.0.0.0"
      , "--host", "172.16.238.10"
      , "--monitoring-port", "6001"
      , "--peer", "172.16.238.20:5001"
      , "--peer", "172.16.238.30:5001"
      , "--hydra-scripts-tx-id", "${HYDRA_SCRIPTS_TX_ID}"
      , "--contestation-period", "${CONTESTATION_PERIOD}"
      , "--hydra-signing-key", "/keys/oscar.sk"
      , "--hydra-verification-key", "/keys/patricia.vk"
      , "--hydra-verification-key", "/keys/rupert.vk"
      , "--cardano-signing-key", "/devnet/credentials/oscar.sk"
      , "--cardano-verification-key", "/devnet/credentials/patricia.vk"
      , "--cardano-verification-key", "/devnet/credentials/rupert.vk"
      , "--ledger-protocol-parameters", "/devnet/protocol-parameters.json"
      , "--testnet-magic", "${TESTNET_MAGIC}"
      , "--node-socket", "/devnet/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.10

  hydra-node-2:
    image: hydra-node:latest
    profiles:
      - hydra-node
      - delegate-server
    volumes:
      - ./data/hydra-keys:/keys:ro
      - ./data/credentials:/devnet/credentials
      - ./${CLUSTER_WORKDIR}:/devnet
    ports:
      - "4002:4001"
    command:
      [ "--node-id", "2"
      , "--api-host", "0.0.0.0"
      , "--host", "172.16.238.20"
      , "--monitoring-port", "6001"
      , "--peer", "172.16.238.10:5001"
      , "--peer", "172.16.238.30:5001"
      , "--hydra-scripts-tx-id", "${HYDRA_SCRIPTS_TX_ID}"
      , "--contestation-period", "${CONTESTATION_PERIOD}"
      , "--hydra-signing-key", "/keys/patricia.sk"
      , "--hydra-verification-key", "/keys/oscar.vk"
      , "--hydra-verification-key", "/keys/rupert.vk"
      , "--cardano-signing-key", "/devnet/credentials/patricia.sk"
      , "--cardano-verification-key", "/devnet/credentials/oscar.vk"
      , "--cardano-verification-key", "/devnet/credentials/rupert.vk"
      , "--ledger-protocol-parameters", "/devnet/protocol-parameters.json"
      , "--testnet-magic", "${TESTNET_MAGIC}"
      , "--node-socket", "/devnet/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.20

  hydra-node-3:
    image: hydra-node:latest
    profiles:
      - hydra-node
      - delegate-server
    volumes:
      - ./data/hydra-keys:/keys:ro
      - ./data/credentials:/devnet/credentials
      - ./${CLUSTER_WORKDIR}:/devnet
    ports:
      - "4003:4001"
    command:
      [ "--node-id", "3"
      , "--api-host", "0.0.0.0"
      , "--host", "172.16.238.30"
      , "--monitoring-port", "6001"
      , "--peer", "172.16.238.10:5001"
      , "--peer", "172.16.238.20:5001"
      , "--hydra-scripts-tx-id", "${HYDRA_SCRIPTS_TX_ID}"
      , "--contestation-period", "${CONTESTATION_PERIOD}"
      , "--hydra-signing-key", "/keys/rupert.sk"
      , "--hydra-verification-key", "/keys/oscar.vk"
      , "--hydra-verification-key", "/keys/patricia.vk"
      , "--cardano-signing-key", "/devnet/credentials/rupert.sk"
      , "--cardano-verification-key", "/devnet/credentials/oscar.vk"
      , "--cardano-verification-key", "/devnet/credentials/patricia.vk"
      , "--ledger-protocol-parameters", "/devnet/protocol-parameters.json"
      , "--testnet-magic", "${TESTNET_MAGIC}"
      , "--node-socket", "/devnet/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.30

  platform-server:
    image: hydra-auction-platform:latest
    profiles:
      - delegate-server
    ports:
      - "8010:8010"
    networks:
      hydra-auction-servers:
    command:
      ["hydra-auction-platform"
      , "--websockets-host", "0.0.0.0:8010"]

  delegate-server-1:
    image: hydra-auction-delegate:latest
    profiles:
      - delegate-server
    depends_on:
      hydra-node-1:
        condition: service_started
      platform-server:
        condition: service_started
    volumes:
      - ./data/hydra-keys:/keys:ro
      - ./data/credentials:/devnet/credentials
      - ./${CLUSTER_WORKDIR}:/devnet
    ports:
      - "8001:8001"
    networks:
      hydra_net:
      hydra-auction-servers:
    environment:
      - HYDRA_SCRIPTS_TX_ID=${HYDRA_SCRIPTS_TX_ID}
    command:
      [ "hydra-auction-delegate"
      , "--platform-server", "platform-server:8010"
      , "--actor", "oscar"
      , "--hydra-node", "172.16.238.10:4001"
      , "--websockets-host", "0.0.0.0:8001"
      , "--network-magic", "${TESTNET_MAGIC}"
      , "--cardano-node-socket", "/devnet/node.socket"
      ]

  delegate-server-2:
    image: hydra-auction-delegate:latest
    profiles:
      - delegate-server
    depends_on:
      hydra-node-2:
        condition: service_started
      platform-server:
        condition: service_started
    volumes:
      - ./data/hydra-keys:/keys:ro
      - ./data/credentials:/devnet/credentials
      - ./${CLUSTER_WORKDIR}:/devnet
    ports:
      - "8002:8001"
    networks:
      hydra_net:
      hydra-auction-servers:
    environment:
      - HYDRA_SCRIPTS_TX_ID=${HYDRA_SCRIPTS_TX_ID}
    command:
      [ "hydra-auction-delegate"
      , "--platform-server", "platform-server:8010"
      , "--actor", "patricia"
      , "--hydra-node", "172.16.238.20:4001"
      , "--websockets-host", "0.0.0.0:8001"
      , "--network-magic", "${TESTNET_MAGIC}"
      , "--cardano-node-socket", "/devnet/node.socket"
      ]

  delegate-server-3:
    image: hydra-auction-delegate:latest
    profiles:
      - delegate-server
    depends_on:
      hydra-node-3:
        condition: service_started
      platform-server:
        condition: service_started
    volumes:
      - ./data/hydra-keys:/keys:ro
      - ./data/credentials:/devnet/credentials
      - ./${CLUSTER_WORKDIR}:/devnet
    ports:
      - "8003:8001"
    networks:
      hydra_net:
      hydra-auction-servers:
    environment:
      - HYDRA_SCRIPTS_TX_ID=${HYDRA_SCRIPTS_TX_ID}
    command:
      [ "hydra-auction-delegate"
      , "--platform-server", "platform-server:8010"
      , "--actor", "rupert"
      , "--hydra-node", "172.16.238.30:4001"
      , "--websockets-host", "0.0.0.0:8001"
      , "--network-magic", "${TESTNET_MAGIC}"
      , "--cardano-node-socket", "/devnet/node.socket"
      ]

networks:
  hydra_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
  hydra-auction-servers:
